<?php $this->extends('../layout.phtml') ?>

<nav class="admin-nav">
	<a href="/admin/pages/" class="<?= $section=='pages' ? 'active' : '' ?>">Pages</a>
	<a href="/admin/files/" class="<?= $section=='files' ? 'active' : '' ?>">Files</a>
	<a href="/admin/users/" class="<?= $section=='users' ? 'active' : '' ?>">Users</a>
	<a href="/admin/bin/"   class="<?= $section=='bin' ? 'active' : '' ?>">Bin</a>
</nav>

<?= $default ?>