<?php $this->extends('layout.phtml', ['title' => 'Log-in', 'section' => null]) ?>

<?php include dirname(__FILE__) . '/_form.phtml' ?>

<div class="login-box">
	<form action="" method="post" class="vertical-form">
		<input type="hidden" name="_nonce" value="<?=\form\generate_nonce('login')?>">

		<?php $this->macro('fieldset', 'email') ?>
			<label for="login-email">Email address</label>
			<input type="text" name="email" id="login-email" value="<?=$this->attr($_POST['email'] ?? '')?>" placeholder="E.g. your@email.edu">
		<?php $this->end() ?>

		<?php $this->macro('fieldset', 'password') ?>
			<label for="login-password">Password</label>
			<input type="password" name="password" id="login-password" placeholder="Your password">
		<?php $this->end() ?>

		<div>
			<button type="submit">Log-in</button>
		</div>
	</form>
</div>